using System.Security.Cryptography;
using System.Text.Json;

namespace Trackside.Updater;

/// <summary>
/// Entry point for the out-of-process Trackside updater boundary.
/// </summary>
public static class Program
{
    /// <summary>
    /// Runs the updater console command.
    /// </summary>
    /// <param name="args">Command-line arguments.</param>
    /// <returns>Zero on success; non-zero on invalid input or failed verification.</returns>
    public static int Main(string[] args) => new UpdaterConsole(Console.Out, Console.Error).Run(args);
}

/// <summary>
/// Minimal command surface used by package smoke tests and future update orchestration.
/// </summary>
public sealed class UpdaterConsole(TextWriter output, TextWriter error)
{
    /// <summary>
    /// Executes the requested updater command.
    /// </summary>
    /// <param name="args">Command-line arguments.</param>
    /// <returns>Zero on success; non-zero on invalid input or failed verification.</returns>
    public int Run(string[] args)
    {
        if (args.Length == 0 || IsHelp(args[0]))
        {
            WriteUsage(output);
            return 0;
        }

        try
        {
            return args[0].ToLowerInvariant() switch
            {
                "inspect" => Inspect(args[1..]),
                "verify" => Verify(args[1..]),
                "plan" => Plan(args[1..]),
                _ => UnknownCommand(args[0]),
            };
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or ArgumentException)
        {
            error.WriteLine(ex.Message);
            return 1;
        }
    }

    private int Inspect(string[] args)
    {
        var manifestPath = RequireOption(args, "--manifest");
        var manifest = BundleManifest.Load(manifestPath);
        output.WriteLine($"Trackside bundle {manifest.BundleVersion} ({manifest.AppVersion})");
        output.WriteLine($"Schema: {manifest.SchemaVersion}");
        output.WriteLine($"Runtime: {manifest.Runtime}");
        output.WriteLine($"Minimum compatible version: {manifest.MinimumCompatibleVersion}");
        output.WriteLine($"Files: {manifest.Files.Count}");
        return 0;
    }

    private int Verify(string[] args)
    {
        var manifestPath = RequireOption(args, "--manifest");
        var bundleRoot = ReadOption(args, "--root") ?? Path.GetDirectoryName(Path.GetFullPath(manifestPath)) ?? Directory.GetCurrentDirectory();
        var manifest = BundleManifest.Load(manifestPath);
        var result = BundleManifestVerifier.Verify(manifest, bundleRoot);
        if (!result.Success)
        {
            foreach (var verificationError in result.Errors)
            {
                error.WriteLine(verificationError);
            }

            return 2;
        }

        output.WriteLine($"Bundle manifest verified: {manifest.BundleVersion} ({manifest.Files.Count} files).");
        return 0;
    }

    private int Plan(string[] args)
    {
        var currentManifestPath = RequireOption(args, "--current");
        var candidateManifestPath = RequireOption(args, "--candidate");
        var current = BundleManifest.Load(currentManifestPath);
        var candidate = BundleManifest.Load(candidateManifestPath);
        var plan = UpdatePlan.Create(current, candidate);
        output.WriteLine(JsonSerializer.Serialize(plan, BundleManifest.JsonOptions));
        return 0;
    }

    private int UnknownCommand(string command)
    {
        error.WriteLine($"Unknown command '{command}'.");
        WriteUsage(error);
        return 1;
    }

    private static bool IsHelp(string value) => value is "-h" or "--help" or "/?";

    private static string RequireOption(string[] args, string optionName) => ReadOption(args, optionName)
        ?? throw new ArgumentException($"Missing required option {optionName}.", optionName);

    private static string? ReadOption(string[] args, string optionName)
    {
        for (var index = 0; index < args.Length - 1; index++)
        {
            if (string.Equals(args[index], optionName, StringComparison.OrdinalIgnoreCase))
            {
                return args[index + 1];
            }
        }

        return null;
    }

    private static void WriteUsage(TextWriter writer)
    {
        writer.WriteLine("Trackside.Updater commands:");
        writer.WriteLine("  inspect --manifest <manifest.json>");
        writer.WriteLine("  verify  --manifest <manifest.json> [--root <bundle-root>]");
        writer.WriteLine("  plan    --current <manifest.json> --candidate <manifest.json>");
    }
}

/// <summary>
/// Versioned Trackside bundle manifest generated by the package script.
/// </summary>
public sealed record BundleManifest
{
    /// <summary>
    /// JSON serializer options shared by scripts, tests, and updater output.
    /// </summary>
    public static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true,
    };

    /// <summary>
    /// Manifest schema version.
    /// </summary>
    public int SchemaVersion { get; init; } = 1;

    /// <summary>
    /// Stable product identifier.
    /// </summary>
    public string AppId { get; init; } = "Gearbox.Trackside";

    /// <summary>
    /// Product version used for assembly and compatibility checks.
    /// </summary>
    public string AppVersion { get; init; } = "0.1.0";

    /// <summary>
    /// Unique versioned bundle identifier.
    /// </summary>
    public string BundleVersion { get; init; } = "0.1.0-local";

    /// <summary>
    /// Oldest app version expected to consume this bundle/update channel.
    /// </summary>
    public string MinimumCompatibleVersion { get; init; } = "0.1.0";

    /// <summary>
    /// Runtime identifier used for published executables.
    /// </summary>
    public string Runtime { get; init; } = "win-x64";

    /// <summary>
    /// UTC time when the bundle was generated.
    /// </summary>
    public DateTimeOffset CreatedUtc { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Installed directory layout expected by scripts.
    /// </summary>
    public BundleInstallLayout InstallLayout { get; init; } = new();

    /// <summary>
    /// Published executable entry points in the bundle.
    /// </summary>
    public BundleEntryPoints EntryPoints { get; init; } = new();

    /// <summary>
    /// Files covered by SHA-256 verification.
    /// </summary>
    public IReadOnlyList<BundleManifestFile> Files { get; init; } = [];

    /// <summary>
    /// Loads a manifest from disk.
    /// </summary>
    /// <param name="manifestPath">Path to a manifest JSON file.</param>
    /// <returns>The deserialized manifest.</returns>
    public static BundleManifest Load(string manifestPath)
    {
        using var stream = File.OpenRead(manifestPath);
        return JsonSerializer.Deserialize<BundleManifest>(stream, JsonOptions)
            ?? throw new JsonException($"Manifest '{manifestPath}' was empty.");
    }
}

/// <summary>
/// Installed directory layout expected by scripts and health output.
/// </summary>
public sealed record BundleInstallLayout
{
    /// <summary>
    /// Read-only application files, separated by binary surface.
    /// </summary>
    public string AppPath { get; init; } = "app";

    /// <summary>
    /// Editable service/tray configuration root.
    /// </summary>
    public string ConfigPath { get; init; } = "config";

    /// <summary>
    /// Durable application data root.
    /// </summary>
    public string DataPath { get; init; } = "data";

    /// <summary>
    /// Runtime logs root.
    /// </summary>
    public string LogsPath { get; init; } = "logs";

    /// <summary>
    /// Update staging root.
    /// </summary>
    public string UpdatesPath { get; init; } = "updates";
}

/// <summary>
/// Published executable entry points in the bundle.
/// </summary>
public sealed record BundleEntryPoints
{
    /// <summary>
    /// Central service executable path relative to the bundle root.
    /// </summary>
    public string Service { get; init; } = "app/service/Trackside.Service.exe";

    /// <summary>
    /// Tray companion executable path relative to the bundle root.
    /// </summary>
    public string Tray { get; init; } = "app/tray/Trackside.Tray.exe";

    /// <summary>
    /// Rig-agent executable path relative to the bundle root.
    /// </summary>
    public string RigAgent { get; init; } = "app/rig-agent/Trackside.RigAgent.exe";

    /// <summary>
    /// Updater executable path relative to the bundle root.
    /// </summary>
    public string Updater { get; init; } = "app/updater/Trackside.Updater.exe";
}

/// <summary>
/// One hash-covered file in a Trackside bundle.
/// </summary>
/// <param name="Path">Forward-slash path relative to the bundle root.</param>
/// <param name="Sha256">Lowercase SHA-256 hex digest.</param>
/// <param name="Bytes">File length in bytes.</param>
public sealed record BundleManifestFile(string Path, string Sha256, long Bytes);

/// <summary>
/// Result of checking a bundle root against a manifest.
/// </summary>
/// <param name="Success">True when all files match.</param>
/// <param name="Errors">Verification errors, if any.</param>
public sealed record BundleVerificationResult(bool Success, IReadOnlyList<string> Errors);

/// <summary>
/// Verifies manifest files against a bundle directory.
/// </summary>
public static class BundleManifestVerifier
{
    /// <summary>
    /// Verifies listed files exist, have the expected length, and match expected SHA-256 hashes.
    /// </summary>
    /// <param name="manifest">Manifest to verify.</param>
    /// <param name="bundleRoot">Bundle root containing the listed files.</param>
    /// <returns>Verification result.</returns>
    public static BundleVerificationResult Verify(BundleManifest manifest, string bundleRoot)
    {
        var errors = new List<string>();
        foreach (var manifestFile in manifest.Files)
        {
            var filePath = System.IO.Path.Combine(bundleRoot, manifestFile.Path.Replace('/', System.IO.Path.DirectorySeparatorChar));
            if (!File.Exists(filePath))
            {
                errors.Add($"Missing file: {manifestFile.Path}");
                continue;
            }

            var fileInfo = new FileInfo(filePath);
            if (fileInfo.Length != manifestFile.Bytes)
            {
                errors.Add($"Size mismatch for {manifestFile.Path}: expected {manifestFile.Bytes}, actual {fileInfo.Length}.");
            }

            using var stream = File.OpenRead(filePath);
            var actualHash = Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();
            if (!string.Equals(actualHash, manifestFile.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                errors.Add($"SHA-256 mismatch for {manifestFile.Path}: expected {manifestFile.Sha256}, actual {actualHash}.");
            }
        }

        return new BundleVerificationResult(errors.Count == 0, errors);
    }
}

/// <summary>
/// Comparison output for a future staff-approved update flow.
/// </summary>
public sealed record UpdatePlan
{
    /// <summary>
    /// Currently installed bundle version.
    /// </summary>
    public string CurrentBundleVersion { get; init; } = string.Empty;

    /// <summary>
    /// Candidate bundle version.
    /// </summary>
    public string CandidateBundleVersion { get; init; } = string.Empty;

    /// <summary>
    /// Planned action.
    /// </summary>
    public string Action { get; init; } = "NoChange";

    /// <summary>
    /// Creates an update plan from two manifests.
    /// </summary>
    /// <param name="current">Current manifest.</param>
    /// <param name="candidate">Candidate manifest.</param>
    /// <returns>Update plan.</returns>
    public static UpdatePlan Create(BundleManifest current, BundleManifest candidate)
    {
        var action = string.Equals(current.BundleVersion, candidate.BundleVersion, StringComparison.OrdinalIgnoreCase)
            ? "NoChange"
            : "UpdateAvailable";

        return new UpdatePlan
        {
            CurrentBundleVersion = current.BundleVersion,
            CandidateBundleVersion = candidate.BundleVersion,
            Action = action,
        };
    }
}